# Semimaro is a simple, responsive Jekyll theme for researchers.
# This config file is used for site settings.
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.profile.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Yohei Hayamizu
copyright: (c) 2024 Yohei Hayamizu
lang: en-US

# Please comment out url variables when you upload the files in _site directory to a web server other than GitHub Pages.
# If you upload your site to https://your-domain.com/site-root, it is as follows:
url: https://yoheihayamizu.github.io
# repository : "yoheihayamizu.github.io"
# baseurl: /

# profile variables are used in About page.
profile:
  name: 速水陽平
  name_en: Yohei Hayamizu
  position: PhD student
  picture: assets/images/profile.jpg
  affiliation: ニューヨーク州立大学ビンガムトン校 コンピュータサイエンス専攻 Autonomous Intelligent Robotics Lab.
  affiliation_en: Autonomous Intelligent Robotics Lab. Department of Computer Science, SUNY Binghamton.
  researcharea: Artificial Intelligence, Robotics, Dialog Systems
  email: yhayami1 "at" binghamton.edu
  # social account setting
  # dribbble: https://dribbble.com/
  researchgate: https://www.researchgate.net/profile/Yohei-Hayamizu
  gscholar: https://scholar.google.com/citations?user=J47eozMAAAAJ
  orcid: https://orcid.org/0000-0003-1642-4919
  github: https://github.com/YoheiHayamizu
  linkedin: https://www.linkedin.com/in/yohei-hayamizu-74539a168
  twitter: https://www.twitter.com/rlmizu
  # flickr: https://www.flickr.com/photos/username
  # instagram: https://instagram.com/username
  # googleplus: https://plus.google.com/username
  # pinterest: https://www.pinterest.com/usename
  # facebook: https://www.facebook.com/hayamizuyohei

# Post-url format setting
# Usage: https://jekyllrb.com/docs/permalinks/
permalink: /post/posts/:categories/:year/:month/:day/:hour-:minute-:second:output_ext

# Navbar item setting
# Nested items make dropdown menu.
navitem:
  -
    - about-en.md
    - about-ja.md
  - publications.md
  - post.md

# If you enable google analytics, comment out the following line:
# google_analytics_tracking_id: xx-xxxxxxxxx-x

# If you enable Disqus comment system, comment out the following line:
# disqus_shortname: your_shortname

# SEO settings by jekyll-seo-tag
# Usage: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
twitter:
  username: *twitter_username
  card: summary

defaults:
  - scope:
      path: ""
    values:
      image: assets/images/profile.jpg # This image is shown in social media posting.

# Build settings
# If you show the excerpts of your posts in top page, please set "show_excerpts: true".
show_excerpts: true
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap